-- AlterEnum
ALTER TYPE "VehicleType" ADD VALUE 'TRACTOR';

-- DropIndex
DROP INDEX "VehicleDetails_listingId_idx";

-- AlterTable
ALTER TABLE "Listing" ADD COLUMN     "bathrooms" DOUBLE PRECISION,
ADD COLUMN     "bedrooms" INTEGER,
ADD COLUMN     "color" TEXT,
ADD COLUMN     "engineNumber" TEXT,
ADD COLUMN     "engineSize" DOUBLE PRECISION,
ADD COLUMN     "floors" INTEGER,
ADD COLUMN     "fuelType" TEXT,
ADD COLUMN     "furnished" BOOLEAN,
ADD COLUMN     "interiorColor" TEXT,
ADD COLUMN     "make" TEXT,
ADD COLUMN     "mileage" DOUBLE PRECISION,
ADD COLUMN     "model" TEXT,
ADD COLUMN     "parkingSpaces" INTEGER,
ADD COLUMN     "size" DOUBLE PRECISION,
ADD COLUMN     "transmission" TEXT,
ADD COLUMN     "utilities" BOOLEAN,
ADD COLUMN     "vin" TEXT,
ADD COLUMN     "year" INTEGER,
ADD COLUMN     "yearBuilt" INTEGER;

-- AlterTable
ALTER TABLE "RealEstateDetails" ADD COLUMN     "accessibilityFeatures" TEXT[] DEFAULT ARRAY[]::TEXT[],
ADD COLUMN     "balcony" BOOLEAN,
ADD COLUMN     "buildingAmenities" TEXT[] DEFAULT ARRAY[]::TEXT[],
ADD COLUMN     "cooling" TEXT,
ADD COLUMN     "elevator" BOOLEAN,
ADD COLUMN     "energyRating" TEXT,
ADD COLUMN     "exposureDirection" TEXT[] DEFAULT ARRAY[]::TEXT[],
ADD COLUMN     "fireSafety" TEXT[] DEFAULT ARRAY[]::TEXT[],
ADD COLUMN     "floor" INTEGER,
ADD COLUMN     "flooringType" TEXT,
ADD COLUMN     "furnished" TEXT,
ADD COLUMN     "heating" TEXT,
ADD COLUMN     "internetIncluded" BOOLEAN,
ADD COLUMN     "parkingType" TEXT,
ADD COLUMN     "petPolicy" TEXT,
ADD COLUMN     "renovationHistory" TEXT,
ADD COLUMN     "securityFeatures" TEXT[] DEFAULT ARRAY[]::TEXT[],
ADD COLUMN     "storage" BOOLEAN,
ADD COLUMN     "storageType" TEXT[] DEFAULT ARRAY[]::TEXT[],
ADD COLUMN     "totalFloors" INTEGER,
ADD COLUMN     "utilities" TEXT[] DEFAULT ARRAY[]::TEXT[],
ADD COLUMN     "view" TEXT,
ADD COLUMN     "windowType" TEXT;

-- AlterTable
ALTER TABLE "User" ADD COLUMN     "city" TEXT,
ADD COLUMN     "dateOfBirth" TEXT,
ADD COLUMN     "street" TEXT;

-- AlterTable
ALTER TABLE "VehicleDetails" ADD COLUMN     "abs" BOOLEAN,
ADD COLUMN     "accessibilityFeatures" TEXT[] DEFAULT ARRAY[]::TEXT[],
ADD COLUMN     "accidentFree" BOOLEAN,
ADD COLUMN     "adaptiveCruiseControl" BOOLEAN,
ADD COLUMN     "adaptiveHeadlights" BOOLEAN,
ADD COLUMN     "additionalNotes" TEXT,
ADD COLUMN     "airConditioning" BOOLEAN,
ADD COLUMN     "airQualitySensor" BOOLEAN,
ADD COLUMN     "airbags" INTEGER,
ADD COLUMN     "aluminumRims" BOOLEAN,
ADD COLUMN     "ambientLighting" BOOLEAN,
ADD COLUMN     "androidAuto" BOOLEAN,
ADD COLUMN     "androidCar" BOOLEAN,
ADD COLUMN     "appleCarPlay" BOOLEAN,
ADD COLUMN     "armrest" BOOLEAN,
ADD COLUMN     "autoDimmingMirrors" BOOLEAN,
ADD COLUMN     "automaticDazzlingInteriorMirrors" BOOLEAN,
ADD COLUMN     "automaticEmergencyBraking" BOOLEAN,
ADD COLUMN     "automaticHighBeams" BOOLEAN,
ADD COLUMN     "automaticStartStop" BOOLEAN,
ADD COLUMN     "axleConfiguration" TEXT,
ADD COLUMN     "bedLength" TEXT,
ADD COLUMN     "blindSpotMonitor" BOOLEAN,
ADD COLUMN     "bluetooth" BOOLEAN,
ADD COLUMN     "bodyFeatures" TEXT[] DEFAULT ARRAY[]::TEXT[],
ADD COLUMN     "bodyStyle" TEXT,
ADD COLUMN     "bodyType" TEXT,
ADD COLUMN     "brakeSystem" TEXT[] DEFAULT ARRAY[]::TEXT[],
ADD COLUMN     "burglarAlarmSystem" BOOLEAN,
ADD COLUMN     "busType" TEXT,
ADD COLUMN     "cabFeatures" TEXT[] DEFAULT ARRAY[]::TEXT[],
ADD COLUMN     "cabType" TEXT,
ADD COLUMN     "camera360" BOOLEAN,
ADD COLUMN     "cargoCapacity" DOUBLE PRECISION,
ADD COLUMN     "cargoFeatures" TEXT[] DEFAULT ARRAY[]::TEXT[],
ADD COLUMN     "cargoVolume" DOUBLE PRECISION,
ADD COLUMN     "cdPlayer" BOOLEAN,
ADD COLUMN     "centralLocking" BOOLEAN,
ADD COLUMN     "certifications" TEXT[] DEFAULT ARRAY[]::TEXT[],
ADD COLUMN     "climateControl" BOOLEAN,
ADD COLUMN     "comfortFeatures" TEXT[] DEFAULT ARRAY[]::TEXT[],
ADD COLUMN     "communicationSystem" TEXT[] DEFAULT ARRAY[]::TEXT[],
ADD COLUMN     "conversionFeatures" TEXT[] DEFAULT ARRAY[]::TEXT[],
ADD COLUMN     "cruiseControl" BOOLEAN,
ADD COLUMN     "curtainAirbags" BOOLEAN,
ADD COLUMN     "customFeatures" TEXT[] DEFAULT ARRAY[]::TEXT[],
ADD COLUMN     "customsCleared" BOOLEAN,
ADD COLUMN     "cylinders" TEXT,
ADD COLUMN     "dabRadio" BOOLEAN,
ADD COLUMN     "dashCam" BOOLEAN,
ADD COLUMN     "daytimeRunningLights" BOOLEAN,
ADD COLUMN     "deadAngleAssistant" BOOLEAN,
ADD COLUMN     "displacement" TEXT,
ADD COLUMN     "distanceTempomat" BOOLEAN,
ADD COLUMN     "distanceWarning" BOOLEAN,
ADD COLUMN     "driveSystem" TEXT,
ADD COLUMN     "driveType" TEXT,
ADD COLUMN     "driverAirbag" BOOLEAN,
ADD COLUMN     "dualZoneClimate" BOOLEAN,
ADD COLUMN     "dvdPlayer" BOOLEAN,
ADD COLUMN     "electricSeats" BOOLEAN,
ADD COLUMN     "electricalSideMirrors" BOOLEAN,
ADD COLUMN     "electricalSystem" TEXT,
ADD COLUMN     "electricalWindowLifter" BOOLEAN,
ADD COLUMN     "electronics" TEXT[] DEFAULT ARRAY[]::TEXT[],
ADD COLUMN     "emergencyBrakeAssist" BOOLEAN,
ADD COLUMN     "emergencyCallSystem" BOOLEAN,
ADD COLUMN     "emergencyExits" INTEGER,
ADD COLUMN     "emissions" TEXT,
ADD COLUMN     "engineConfiguration" TEXT,
ADD COLUMN     "engineManufacturer" TEXT,
ADD COLUMN     "engineModel" TEXT,
ADD COLUMN     "engineNumber" TEXT,
ADD COLUMN     "enginePowerOutput" TEXT,
ADD COLUMN     "engineSpecs" TEXT[] DEFAULT ARRAY[]::TEXT[],
ADD COLUMN     "engineType" TEXT,
ADD COLUMN     "entertainmentSystem" TEXT[] DEFAULT ARRAY[]::TEXT[],
ADD COLUMN     "esp" BOOLEAN,
ADD COLUMN     "exteriorFeatures" TEXT[] DEFAULT ARRAY[]::TEXT[],
ADD COLUMN     "fatigueWarningSystem" BOOLEAN,
ADD COLUMN     "fogLights" BOOLEAN,
ADD COLUMN     "frameType" TEXT,
ADD COLUMN     "frontAirbags" BOOLEAN,
ADD COLUMN     "frontAttachments" TEXT[] DEFAULT ARRAY[]::TEXT[],
ADD COLUMN     "frontSuspension" TEXT[] DEFAULT ARRAY[]::TEXT[],
ADD COLUMN     "fuelTankCapacity" TEXT,
ADD COLUMN     "glarelessHighBeam" BOOLEAN,
ADD COLUMN     "gvwr" DOUBLE PRECISION,
ADD COLUMN     "handlebarType" TEXT,
ADD COLUMN     "handsFreeCalling" BOOLEAN,
ADD COLUMN     "headUpDisplay" BOOLEAN,
ADD COLUMN     "headlightCleaning" BOOLEAN,
ADD COLUMN     "heatedSeats" BOOLEAN,
ADD COLUMN     "highBeamAssistant" BOOLEAN,
ADD COLUMN     "hitchCapacity" INTEGER,
ADD COLUMN     "horsepower" INTEGER,
ADD COLUMN     "hours" INTEGER,
ADD COLUMN     "hydraulicFlow" INTEGER,
ADD COLUMN     "hydraulicOutlets" TEXT[] DEFAULT ARRAY[]::TEXT[],
ADD COLUMN     "hydraulicSystem" TEXT,
ADD COLUMN     "immobilizer" BOOLEAN,
ADD COLUMN     "importStatus" TEXT,
ADD COLUMN     "instrumentCluster" TEXT[] DEFAULT ARRAY[]::TEXT[],
ADD COLUMN     "insuranceType" TEXT,
ADD COLUMN     "integratedMusicStreaming" BOOLEAN,
ADD COLUMN     "interiorHeight" TEXT,
ADD COLUMN     "interiorLength" TEXT,
ADD COLUMN     "isofix" BOOLEAN,
ADD COLUMN     "keylessEntry" BOOLEAN,
ADD COLUMN     "kneeAirbags" BOOLEAN,
ADD COLUMN     "laneAssist" BOOLEAN,
ADD COLUMN     "laneDepartureWarning" BOOLEAN,
ADD COLUMN     "laneKeepAssist" BOOLEAN,
ADD COLUMN     "lastInspectionDate" TEXT,
ADD COLUMN     "leatherSteeringWheel" BOOLEAN,
ADD COLUMN     "ledDaytimeRunningLights" BOOLEAN,
ADD COLUMN     "ledHeadlights" BOOLEAN,
ADD COLUMN     "lightSensor" BOOLEAN,
ADD COLUMN     "lighting" TEXT[] DEFAULT ARRAY[]::TEXT[],
ADD COLUMN     "lightingSystem" TEXT[] DEFAULT ARRAY[]::TEXT[],
ADD COLUMN     "luggageCompartmentSeparation" BOOLEAN,
ADD COLUMN     "luggageCompartments" INTEGER,
ADD COLUMN     "luggageRacks" BOOLEAN,
ADD COLUMN     "luggageSpace" DOUBLE PRECISION,
ADD COLUMN     "lumbarSupport" BOOLEAN,
ADD COLUMN     "maintenanceHistory" TEXT,
ADD COLUMN     "modifications" TEXT[] DEFAULT ARRAY[]::TEXT[],
ADD COLUMN     "monitor" TEXT[] DEFAULT ARRAY[]::TEXT[],
ADD COLUMN     "motorcycleType" TEXT,
ADD COLUMN     "mountainDrivingAssistant" BOOLEAN,
ADD COLUMN     "multifunctionalSteeringWheel" BOOLEAN,
ADD COLUMN     "navigationSystem" TEXT,
ADD COLUMN     "nightVision" BOOLEAN,
ADD COLUMN     "onBoardComputer" BOOLEAN,
ADD COLUMN     "parkingAid" BOOLEAN,
ADD COLUMN     "parkingAidCamera" BOOLEAN,
ADD COLUMN     "parkingAidSensorsFront" BOOLEAN,
ADD COLUMN     "parkingAidSensorsRear" BOOLEAN,
ADD COLUMN     "parkingAssist" TEXT[] DEFAULT ARRAY[]::TEXT[],
ADD COLUMN     "parkingSensors" BOOLEAN,
ADD COLUMN     "passengerAirbag" BOOLEAN,
ADD COLUMN     "passengerFeatures" TEXT[] DEFAULT ARRAY[]::TEXT[],
ADD COLUMN     "payload" DOUBLE PRECISION,
ADD COLUMN     "performanceFeatures" TEXT[] DEFAULT ARRAY[]::TEXT[],
ADD COLUMN     "powerSteering" BOOLEAN,
ADD COLUMN     "powerTailgate" BOOLEAN,
ADD COLUMN     "precisionFarming" TEXT[] DEFAULT ARRAY[]::TEXT[],
ADD COLUMN     "premiumSound" BOOLEAN,
ADD COLUMN     "protectiveEquipment" TEXT[] DEFAULT ARRAY[]::TEXT[],
ADD COLUMN     "ptoHorsepower" INTEGER,
ADD COLUMN     "ptoSystem" TEXT[] DEFAULT ARRAY[]::TEXT[],
ADD COLUMN     "radio" BOOLEAN,
ADD COLUMN     "rainSensingWipers" BOOLEAN,
ADD COLUMN     "rainSensor" BOOLEAN,
ADD COLUMN     "rearAC" BOOLEAN,
ADD COLUMN     "rearAttachments" TEXT[] DEFAULT ARRAY[]::TEXT[],
ADD COLUMN     "rearCamera" BOOLEAN,
ADD COLUMN     "rearSeatEntertainment" BOOLEAN,
ADD COLUMN     "rearSuspension" TEXT[] DEFAULT ARRAY[]::TEXT[],
ADD COLUMN     "registrationExpiry" TEXT,
ADD COLUMN     "remoteStart" BOOLEAN,
ADD COLUMN     "riderAids" TEXT[] DEFAULT ARRAY[]::TEXT[],
ADD COLUMN     "ridingStyle" TEXT,
ADD COLUMN     "roofHeight" TEXT,
ADD COLUMN     "roofType" TEXT,
ADD COLUMN     "safetyFeatures" TEXT[] DEFAULT ARRAY[]::TEXT[],
ADD COLUMN     "seatHeight" INTEGER,
ADD COLUMN     "seating" TEXT[] DEFAULT ARRAY[]::TEXT[],
ADD COLUMN     "seatingCapacity" INTEGER,
ADD COLUMN     "serviceHistoryDetails" TEXT,
ADD COLUMN     "sideAirbag" BOOLEAN,
ADD COLUMN     "sideAirbags" BOOLEAN,
ADD COLUMN     "soundSystem" BOOLEAN,
ADD COLUMN     "spareKey" BOOLEAN,
ADD COLUMN     "speedLimitingSystem" BOOLEAN,
ADD COLUMN     "startType" TEXT,
ADD COLUMN     "startingSystem" TEXT,
ADD COLUMN     "steeringSystem" TEXT[] DEFAULT ARRAY[]::TEXT[],
ADD COLUMN     "steeringType" TEXT,
ADD COLUMN     "storageOptions" TEXT[] DEFAULT ARRAY[]::TEXT[],
ADD COLUMN     "summerTires" BOOLEAN,
ADD COLUMN     "sunroof" BOOLEAN,
ADD COLUMN     "suspensionType" TEXT,
ADD COLUMN     "switchingRockers" BOOLEAN,
ADD COLUMN     "threePointHitch" TEXT,
ADD COLUMN     "tireCondition" TEXT,
ADD COLUMN     "tirePressureMonitoring" BOOLEAN,
ADD COLUMN     "tireType" TEXT,
ADD COLUMN     "torque" INTEGER,
ADD COLUMN     "touchscreen" BOOLEAN,
ADD COLUMN     "towingCapacity" DOUBLE PRECISION,
ADD COLUMN     "trackHoldingAssistant" BOOLEAN,
ADD COLUMN     "tractionControl" BOOLEAN,
ADD COLUMN     "trafficSignRecognition" BOOLEAN,
ADD COLUMN     "truckType" TEXT,
ADD COLUMN     "trunkCapacity" DOUBLE PRECISION,
ADD COLUMN     "twoZoneClimateControl" BOOLEAN,
ADD COLUMN     "upholsteryMaterial" TEXT,
ADD COLUMN     "usbPorts" BOOLEAN,
ADD COLUMN     "vanType" TEXT,
ADD COLUMN     "ventilatedSeats" BOOLEAN,
ADD COLUMN     "vin" TEXT,
ADD COLUMN     "voiceControl" BOOLEAN,
ADD COLUMN     "warrantyPeriod" TEXT,
ADD COLUMN     "wheelSize" TEXT,
ADD COLUMN     "wheelType" TEXT,
ADD COLUMN     "wheelbase" TEXT,
ADD COLUMN     "wheelchairAccessible" BOOLEAN,
ADD COLUMN     "wheelchairLift" BOOLEAN,
ADD COLUMN     "wifiHotspot" BOOLEAN,
ADD COLUMN     "wirelessCharging" BOOLEAN,
ALTER COLUMN "warranty" SET DATA TYPE TEXT;
