export const apartmentEssentialFields = [
  "condition",
  "floor",
  "totalFloors",
  "parking",
  "elevator",
  "price",
  "size",
  "bedrooms",
  "bathrooms",
];

export const apartmentAdvancedFields = [
  "balcony",
  "storage",
  "heating",
  "cooling",
  "buildingAmenities",
  "energyRating",
  "furnished",
  "petPolicy",
  "view",
  "securityFeatures",
  "fireSafety",
  "flooringType",
  "internetIncluded",
  "windowType",
  "accessibilityFeatures",
  "kitchenFeatures",
  "bathroomFeatures",
  "renovationHistory",
  "nearbyAmenities",
  "leaseTerms",
  "soundproofing",
  "viewType",
  "parkingType",
  "utilities",
  "smartHomeFeatures",
  "communityFeatures",
  "exposureDirection",
  "storageType",
];

export const apartmentFieldNames = [
  ...apartmentEssentialFields,
  ...apartmentAdvancedFields,
];
