export const commonEssentialFields = [
  "color",
  "interiorColor",
  "condition",
  "previousOwners",
  "registrationStatus",
  "engine",
  "fuelType",
  "transmissionType",
  "serviceHistory",
  "hours",
  "horsepower",
  "driveSystem",
  "emissions",
  "warranty",
];
